# Generated by Django 5.1.7 on 2025-03-29 10:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DocumentType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nome")),
            ],
            options={
                "verbose_name": "Tipo de Documento",
                "verbose_name_plural": "Tipos de Documentos",
            },
        ),
        migrations.CreateModel(
            name="ExtractionRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "request_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Data da Solicitação",
                    ),
                ),
                (
                    "requested_by",
                    models.CharField(max_length=100, verbose_name="Solicitado por"),
                ),
                (
                    "additional_info",
                    models.TextField(
                        blank=True, null=True, verbose_name="Informações Adicionais"
                    ),
                ),
            ],
            options={
                "verbose_name": "Solicitação de Extração",
                "verbose_name_plural": "Solicitações de Extração",
            },
        ),
        migrations.CreateModel(
            name="ProcedureType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nome")),
            ],
            options={
                "verbose_name": "Tipo de Procedimento",
                "verbose_name_plural": "Tipos de Procedimentos",
            },
        ),
        migrations.CreateModel(
            name="ExtractionRequestDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField(verbose_name="Ano")),
                ("number", models.IntegerField(verbose_name="Número")),
                (
                    "attached_file",
                    models.FileField(
                        upload_to="documents/", verbose_name="Arquivo Anexo"
                    ),
                ),
                (
                    "additional_info",
                    models.TextField(
                        blank=True, null=True, verbose_name="Informações Adicionais"
                    ),
                ),
                (
                    "document_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="extraction.documenttype",
                        verbose_name="Tipo de Documento",
                    ),
                ),
                (
                    "extraction_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="extraction.extractionrequest",
                        verbose_name="Solicitação de Extração",
                    ),
                ),
            ],
            options={
                "verbose_name": "Documento da Solicitação",
                "verbose_name_plural": "Documentos da Solicitação",
            },
        ),
        migrations.CreateModel(
            name="ExtractionRequestProcedure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField(verbose_name="Ano")),
                ("number", models.IntegerField(verbose_name="Número")),
                (
                    "additional_info",
                    models.TextField(
                        blank=True, null=True, verbose_name="Informações Adicionais"
                    ),
                ),
                (
                    "extraction_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="procedures",
                        to="extraction.extractionrequest",
                        verbose_name="Solicitação de Extração",
                    ),
                ),
                (
                    "procedure_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="extraction.proceduretype",
                        verbose_name="Tipo de Procedimento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Procedimento da Solicitação",
                "verbose_name_plural": "Procedimentos da Solicitação",
            },
        ),
    ]
