# Generated by Django 5.1.7 on 2025-03-29 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("extraction", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganizationUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nome")),
                (
                    "code",
                    models.CharField(max_length=20, unique=True, verbose_name="Código"),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="extraction.organizationunit",
                        verbose_name="Unidade Superior",
                    ),
                ),
            ],
            options={
                "verbose_name": "Unidade Organizacional",
                "verbose_name_plural": "Unidades Organizacionais",
            },
        ),
        migrations.AddField(
            model_name="extractionrequest",
            name="organization_unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="extraction_requests",
                to="extraction.organizationunit",
                verbose_name="Unidade Organizacional",
            ),
        ),
    ]
