# Generated by Django 5.1.7 on 2025-03-29 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("extraction", "0003_initial_organization_units"),
    ]

    operations = [
        migrations.AddField(
            model_name="extractionrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Pendente de Envio"),
                    ("requested", "Solicitada"),
                    ("approved", "Aprovada"),
                    ("rejected", "Rejeitada"),
                    ("in_progress", "Em Andamento"),
                    ("completed", "Finalizada"),
                    ("failed", "Finalizada - Falhou"),
                    ("success", "Finalizada - Sucesso"),
                ],
                default="draft",
                editable=False,
                max_length=20,
                verbose_name="Status",
            ),
        ),
    ]
