# Generated by Django 5.1.7 on 2025-03-29 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("extraction", "0004_extractionrequest_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="extractionrequest",
            name="justification",
            field=models.TextField(
                blank=True, null=True, verbose_name="Justificativa da Decisão"
            ),
        ),
    ]
