# Generated by Django 5.1.7 on 2025-03-29 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("extraction", "0006_auto_20250329_1208"),
    ]

    operations = [
        migrations.AddField(
            model_name="documenttype",
            name="code",
            field=models.CharField(
                default="DOC", max_length=20, unique=True, verbose_name="Código"
            ),
        ),
        migrations.AddField(
            model_name="proceduretype",
            name="code",
            field=models.CharField(
                default="PROC", max_length=20, unique=True, verbose_name="Código"
            ),
        ),
    ]
